"""Icon for the following action: remove/removed operation."""

# This icon was converted from the Oxygen Icon Theme
# Please see copyright for further informations

icon = """
iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAMAAADzapwJAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAN
1wAADdcBQiibeAAAAAd0SU1FB9kMBhQQEFUkXAMAAAECUExURQAAAHwTE4UUFJAWFqYiIqwODv8A
AP///0UAAEQAAEcAAFoAAGUAAGQAAGQAAGUAAJI8PJM8PGkAAGoAAGoAAJM9PZI8PI87O5A6Oo86
Oo87O+rf3+3n5+////D///H///L///P///T///X///b///f///j///n///r///v///Dy8vD09PHy
8vH09PL09O3t7e7u7vDs7PT29vP19fP29vb5+fX394xPT5tPT61PT08AAFAAAFEAAFcAAFkAAF8A
AGUAAGYAAGkAAGoAAGsAAHEAAHoAAHsAAIMAAIgAAIkAAIwAAJcAAJ4AAKgAALAAALkAAMAAAMkA
AM4AANMAANYAANZTrScAAAA6dFJOUwAAAAAAAAAACgwMDxMxMzNFRUZGR0dIVFRVVaGsra2tra2t
ra2tra2trbCwsLCwsrK1v8DAxMXf3988ExMrAAAAAWJLR0QHFmGI6wAAAL9JREFUeNqVkbsOwjAM
Re3EaSlCFTNi5f+/CgmGSoiHqtaNjSkiJCoLdzw5vncIQIBFEDC4sPaYMRnGaSLeHLwUrjt1kaDx
rJzRgLtbT0CiTStfl3s1aP3cXmLCfnutsaJ5JdYJDzLfwCL/YCX9YMyxT9jpL1sL7OCDixJclqSh
dJIy2/SeuYuKKqDDBmDGEarHPrhXVCxdDToSDOge3csVKzB9RTiazeedroryI9t75SkUn8asEcHZ
cZXh0QanJ9B2UzvXaeeHAAAAAElFTkSuQmCC
"""
