name: Python linter

on:
  - push
  - pull_request

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: Python linter installation
        run: pip install --user pylint
      - name: Python linter
        run: pylint ols/
